version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies"
      - dotnet restore

  pre_build:
    commands:
      - echo "Running pre-build scripts"
      - dotnet build --configuration Release

  build:
    commands:
      - echo "Building the application"
      - dotnet publish -c Release -o ./publish

  post_build:
    commands:
      - echo "Build completed, now packaging the application"
      - zip -r app.zip ./publish
      - echo "Saving the build output"

artifacts:
  files:
    - app.zip
  discard-paths: yes
  base-directory: ./publish
