FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dotnet-build
WORKDIR /src
COPY CatalogService/ ./CatalogService/
COPY GrpcContracts/ ./GrpcContracts/
RUN dotnet restore CatalogService/CatalogService/CatalogService.csproj
RUN dotnet publish CatalogService/CatalogService/CatalogService.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=dotnet-build /app/publish .
EXPOSE 80
ENTRYPOINT ["dotnet", "CatalogService.dll"]

